CONF_CALIBRATION_PATH: calibrations/default_spherical.yaml
CONF_CAMERA_USE: true
CONF_CAMERA_DEVICES:
  fish_embedded:
    api: vxpy.devices.camera.virtual_camera
    serial: 1234
    model: Single_Fish_Spontaneous_1_115fps
    dtype: RGB8
    width: 640
    height: 480
    framerate: 115
    exposure: 5.0
    gain: 1.5
    preload_file: False
  multiple_fish:
    api: vxpy.devices.camera.virtual_camera
    serial: 5678
    model: Multi_Fish_Eyes_Cam_20fps
    dtype: Y800
    width: 752
    height: 480
    framerate: 20
    exposure: 2.0
    gain: 5.5
    preload_file: False
CONF_CAMERA_ROUTINES:
- vxpy.routines.camera_capture.Frames
- vxpy.routines.zf_tracking.EyePositionDetection
CONF_DISPLAY_USE: true
CONF_DISPLAY_FPS: 60
CONF_DISPLAY_ROUTINES:
- vxpy.routines.display_capture.Frames
- vxpy.routines.display_capture.Parameters
CONF_GUI_USE: true
CONF_GUI_SCREEN: 0
CONF_GUI_ADDONS:
  Camera:
  - vxpy.addons.frames_widgets.FrameStream
  - vxpy.addons.zf_tracking_widgets.EyePositionDetector
  Display:
  - vxpy.addons.display_widgets.VisualInteractor
  Io:
  - vxpy.addons.io_core_widgets.DisplayPSD
CONF_IO_USE: true
CONF_IO_PINS:
  sawtooth_analogin:
    device: Dev1
    type: ai
    map: ai2
  saccade_trigger_out:
    device: Dev1
    type: do
    map: do5
  rectangular_analogin:
    device: Dev2
    type: ai
    map: ai01
CONF_IO_MAX_SR: 1000
CONF_IO_DEVICES:
  Dev1:
    type: virtual_daq
    model: VirtualDaqDevice
    port: COM3
  Dev2:
    type: virtual_daq
    model: VirtualDaqDevice
    port: COM6
CONF_IO_ROUTINES:
- vxpy.routines.read_inputs.ReadAll
- vxpy.routines.write_test_attributes.SinesAddedWhiteNoise
- vxpy.routines.write_test_attributes.WriteRandoms
CONF_WORKER_USE: true
CONF_WORKER_ROUTINES:
- vxpy.routines.calculate_csd.CalculatePSD
CONF_REC_ENABLE: true
CONF_REC_OUTPUT_FOLDER: recordings
CONF_REC_ATTRIBUTES:
- var_param*
- eyepos_*
- fish_embedded_frame
- multiple_fish_frame
- test_sines_whitenoise
- sawtooth_analogin
- particle_*
