CONF_CALIBRATION_PATH: calibrations/default_spherical.yaml
CONF_CAMERA_USE: true
CONF_CAMERA_DEVICES:
  fish_embedded:
    api: vxpy.devices.camera.virtual_camera.VirtualCamera
    data_source: HDF5
    data_path: Single_Fish_Spontaneous_1_115fps
    preload_data: False
    width: 720
    height: 480
    frame_rate: 115
  multiple_fish_vertical_swim:
    api: vxpy.devices.camera.virtual_camera.VirtualCamera
    data_source: HDF5
    data_path: Multi_Fish_Vertical_Swim_10fps
    preload_data: False
    width: 1920
    height: 1080
    frame_rate: 10
  multiple_fish_embedded:
    api: vxpy.devices.camera.virtual_camera.VirtualCamera
    data_source: HDF5
    data_path: Multi_Fish_Eyes_Cam_20fps
    preload_data: False
    width: 752
    height: 480
    frame_rate: 20
CONF_CAMERA_ROUTINES:
- vxpy.routines.camera_capture.Frames
- vxpy.routines.zf_tracking.EyePositionDetection
CONF_DISPLAY_USE: true
CONF_DISPLAY_FPS: 60
CONF_DISPLAY_ROUTINES:
- vxpy.routines.display_capture.Frames
- vxpy.routines.display_capture.Parameters
CONF_GUI_USE: true
CONF_GUI_SCREEN: 0
CONF_GUI_ADDONS:
  Camera:
  - vxpy.addons.frames_widgets.FrameStream
  - vxpy.addons.zf_tracking_widgets.EyePositionDetector
  Display:
  - vxpy.addons.display_widgets.VisualInteractor
  Io:
  - vxpy.addons.io_core_widgets.DisplayPSD
CONF_IO_USE: true
CONF_IO_DEVICES:
  Dev1_virtual:
    api: vxpy.devices.virtual_daq.VirtualDaqDevice
    pins:
      on_off_1s_di:
        signal: di
        fun: on_off
        args:
          freq: 0.5
          t_offset: 0.0
  Dev2_arduino:
    api: vxpy.devices.arduino_daq.ArduinoDaq
    model: ArduinoNano
    port: /dev/ttyUSB0
    pins:
      saccade_trigger_out:
        type: digital_out
        map: d:4:o
      Ext_trigger01:
        type: digital_in
        map: d:10:i
CONF_IO_MAX_SR: 1000
CONF_IO_ROUTINES:
- vxpy.routines.read_inputs.ReadAll
CONF_WORKER_USE: true
CONF_WORKER_ROUTINES:
- vxpy.routines.calculate_csd.CalculatePSD
CONF_REC_ENABLE: true
CONF_REC_OUTPUT_FOLDER: recordings
CONF_REC_ATTRIBUTES:
- eyepos_*
- ~*_frame
- test_sines_whitenoise
- sawtooth_analogin
